variables:
  TEST_SECRET: secret
test:
  image: python:2.7
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  script:
    - PYTHONPATH="${PYTHONPATH}:./src/" python src/test.py && PYTHONPATH="${PYTHONPATH}:./src/" coverage run --source=./src/ src/test.py && coverage report -m

test_py3:
  image: python:3.5
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  script:
    - PYTHONPATH="${PYTHONPATH}:./src/" python src/test.py && PYTHONPATH="${PYTHONPATH}:./src/" coverage run --source=./src/ src/test.py && coverage report -m
  allow_failure: true

test_package_py2:
  image: python:2.7
  script:
    - pip install --upgrade .

test_package_py3:
  image: python:3.5
  script:
    - pip install --upgrade .
  allow_failure: true